# Generated by Django 5.1.1 on 2024-09-13 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default=datetime.datetime.now, max_length=100, null=True),
        ),
    ]
